### ISSUE TITLE
Thông báo hoàn thành đồ án

### ISSUE THREAD

**Issue by grevyarlesp** [grevyarlesp/HCMUS_P4DS_Final#1]
Nhóm đã hoàn thành đồ án cho các yêu cầu trong đề bài. 

Phiên bản hoàn thành nằm ở commit 85f02b6 trên branch master. 

Mời các bạn nhận xét và góp ý.

**Comment by MinhThien28** [comment]
Chào các bạn,
Theo mình, phần tiền xử lý và giải thích dữ liệu khá đầy đủ và dễ hiểu.
Về phần các câu hỏi, cá nhân mình cảm thấy có một số câu hỏi khá dễ để trả lời. Ví dụ như ở câu 2 chỉ cần thực hiện thao tác lọc là ta đã có thể trả lời được câu hỏi này, cảm giác như câu hỏi mang quá nhiều tính chất thống kê chứ không nhằm vào mục đích nghiên cứu để tìm ra bản chất của vấn đề.
Cần thêm phần nhận xét cho các câu hỏi sau khi vẽ biểu đồ bởi nếu là một người không am hiểu nhiều về vấn đề này nhìn vào biểu đồ sẽ không hiểu rõ và tường tận được.

**Comment by anv0101** [comment]
Chào các bạn mình là An đến từ nhóm 10 xin góp 1 chút ý kiến cho các bạn:
- Về phần thu thập dữ liệu và khám phá dữ liệu mình thấy các bạn làm khá đầy đủ 
- Về phần câu hỏi thì mình thấy phần  phân tích câu hỏi của các bạn còn khá hạn chế không biết là do các bạn chưa làm xong hay sao 
-  Ví dụ như câu 2 mình thấy các bạn chỉ hiện ra cái bảng danh sách các ngôn ngữ lập trình ngoài việc giải thích ý nghĩa câu hỏi thì các bạn có thể tham khảo ý kiến của mình là thử tìm hiểu tại sao những ngôn ngữ đó lại được sử dụng nhiều như vậy nó có dễ học hay không và đưa ra lời khuyên là nên chọn ngôn ngữ lập trình nào để học hoặc mở rộng vấn đề lên nữa là những ngôn ngữ đó phù hợp cho những chuyên ngành  hay công việc cụ thể nào ?

**Comment by tamanh-19127330** [comment]
Chào các bạn mình là Tâm Anh nhóm 10 sau đây mình xin để lại mốt số ý kiến như sau : 
- Nhìn chung thì mình thấy đồ án của các bạn đều hoàn toàn được viết bằng tiếng anh đây là điểm khiến mình khá ấn tượng .Về phần đầu tiên là tiền xử lý và giải thích ý nghĩa của mỗi từng cột dữ liệu thì mình thấy các bạn cũng đã ghi khá đầy đủ, tuy nhiên mình cũng đồng ý kiến với bạn Thiện ở trên là các câu hỏi khá dễ để trả lời dẫn đến việc ở các câu hỏi thì các bạn trả lời cũng khá ngắn gọn vì hầu như cũng không có gì nhiều để phân tích thêm, ngoài ra thì mình thấy phần nhận xét ở mỗi hình các bạn nhận xét khá đơn giản mình nghĩ các bạn nên cố gắng để phân tích nhiều hơn như ở câu 1 thì ngoài việc chỉ viết ra nước nào có số lượng cao nhất thì các bạn nên viết thêm một vài nước khác hoặc cũng có thể tìm hiểu thêm tại sao lại xếp hạng như vậy chẳng hạn
- Cuối cùng mình thấy các bạn vẽ khá nhiều cùng 1 loại biểu đồ, mình nghĩ các bạn nên vẽ đa dạng hơn để có nhiều góc nhìn khác nhau 
Bên trên là một vài ý kiến đóng góp của mình nếu có gì sai sót mong các bạn thông cảm

**Comment by Khacvy1707** [comment]
>

**Comment by Khacvy1707** [comment]
Mình cảm ơn ý kiến của các bạn, nhóm mình sẽ xem sét lại những điều các bạn góp ý.
